### ISSUE TITLE
Error with beta 1.24.0-10.2.pre

### ISSUE THREAD

**Issue by ElaineSchwner** [HunterVillage/multiple_select#9]
Hi, I just upgraded Flutter  Flutter (Channel beta, 1.24.0-10.2.pre,

and I am getting this error (trying to run on web):

../../../.pub-cache/hosted/pub.dartlang.org/multiple_select-0.1.23/lib/multiple_select.dart:72:41: Error: No named parameter with the name 'shadowThemeOnly'.
    ThemeData theme = Theme.of(context, shadowThemeOnly: true);
                                        ^^^^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^

Any idea how I can correct this?

Thank you.

**Comment by dave-k** [comment]
@ElaineSchwner Did you resolve this issue?

 I am also getting this error after upgrading to the latest package versions

````
.pub-cache/hosted/pub.dartlang.org/multiple_select-0.1.24/lib/multiple_select.dart:72:41: Error: No named parameter with the name 'shadowThemeOnly'.
    ThemeData theme = Theme.of(context, shadowThemeOnly: true);         
                                        ^^^^^^^^^^^^^^^                 
../../../development/flutter/packages/flutter/lib/src/material/theme.dart:107:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {                           
````

pubspec.yaml
````
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places:
    path: ./lib/plugins/flutter_google_places
  auto_size_text: ^2.1.0
  cached_network_image: ^2.5.0
  camera: ^0.6.2+1
  cloud_firestore: ^0.14.4
  cloud_functions: ^0.7.2
  cupertino_icons: ^0.1.3
  date_field: ^0.3.3
  datetime_picker_formfield: ^1.0.0
  email_validator: ^1.0.6
  enum_to_string: ^1.0.14
  firebase_auth: ^0.18.4+1
  firebase_auth_web: ^0.3.2+3
  firebase_core: ^0.5.3
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.2.0
  flutter_holo_date_picker: ^0.3.0
  flutter_hooks: ^0.15.0
  flutter_launcher_icons: ^0.8.1
  flutter_multiselect: ^0.5.1
  flutter_range_slider: ^1.5.0
  flutter_sms: ^2.1.1
  flutter_spinkit: ^4.1.2+1
  flutter_tindercard: ^0.2.0
  font_awesome_flutter: ^8.11.0
  geocoder: ^0.2.1
  geocoding: ^1.0.5
  geolocator: ^6.1.13
  get: ^3.24.0
  google_maps_flutter: ^1.0.6
  google_sign_in: ^4.5.6
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+17
  location: ^3.2.1
  mask_text_input_formatter: ^1.2.1
  multiple_select: ^0.1.24
  multiselect_formfield: ^0.1.5
  numberpicker: ^1.3.0
  package_info: ^0.4.3+2
  path: ^1.7.0
  pin_code_fields: ^6.0.1
  pin_entry_text_field: ^0.1.4
  provider: ^4.3.2+3
  rflutter_alert: ^1.1.0
  shared_preferences: ^0.5.12+4
  strings: ^0.1.4
  url_launcher: ^5.7.10
  video_player: ^1.0.1
````

````
$ flutter --version
Flutter 1.26.0-2.0.pre.137 • channel master • https://github.com/flutter/flutter.git
Framework • revision 8f5d0371af (21 hours ago) • 2020-12-26 11:07:36 +0330
Engine • revision f5364860ab
Tools • Dart 2.12.0 (build 2.12.0-179.0.dev)
````
````
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-2.0.pre.137, on macOS 11.2 20D5029f darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
$ 
````
